//payment approved page
"use client"
import axios, { AxiosError } from "axios";
import Head from "next/head";
import { useMutation } from "react-query";

// Path: app/payment/approved/page.tsx

async function getData(orderID:any) {
    const data = orderID.query
    const res = await fetch(`https://api-m.paypal.com/v2/checkout/orders/${data}`);
    console.log('res is ' ,res)
    // The return value is *not* serialized
    // You can return Date, Map, Set, etc.
  
    // Recommendation: handle errors
    if (!res.ok) {
      // This will activate the closest `error.js` Error Boundary
      throw new Error('Failed to fetch data');
    }
  
    return res.json();
  }

 

export default function Home(orderID : {orderID:any}) {
    
    //get orderID from query string
    
    //extract orderID from query string
     
    console.log('data is ' ,orderID)
    //get data from paypal
    
    // getData(orderID)
    
    
    return (
        <div className='container'>
        <Head>
            <title>Payment Approved</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    
        <main className='  '>
            <h1>Payment Approved</h1>
            {/* <p>Order ID: {data.orderID}</p>
            <p>Payment ID: {data.paymentID}</p>
            <p>Payment Token: {data.paymentToken}</p>
            <p>Return URL: {data.returnUrl}</p> */}
        </main>
    
        <footer className=' '>
            <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            >
            Powered by{' '}
            
            </a>
        </footer>
        </div>
    )
}